const reasons = [
    "Your smile brightens up my day.",
    "Your kindness is truly special.",
    "Your intelligence is inspiring.",
    "The way you care for others is heartwarming.",
    "You have a beautiful soul.",
    "Your positivity is contagious.",
    "You make every moment memorable.",
    "Your laughter is music to my ears.",
    "Your sense of humor never fails to make me smile.",
    "You're always there for me, no matter what.",
    "The way you look at the world with wonder is enchanting.",
    "Your determination to achieve your goals is admirable.",
    "You have a unique and captivating personality.",
    "You're not afraid to be yourself, and I love that.",
    "The way you handle challenges with grace is impressive.",
    "Your generosity knows no bounds.",
    "Your presence brings joy to any room.",
    "You have a way of making ordinary moments extraordinary.",
    "Your passion for life is invigorating.",
    "You're a constant source of inspiration.",
    "Your empathy and compassion make you truly beautiful.",
    "The way you express your thoughts and feelings is eloquent.",
    "You have a heart of gold.",
    "Your inner strength is remarkable.",
    "You radiate confidence in everything you do.",
    "Your creativity knows no limits.",
    "You're a beacon of light in my life.",
    "Your resilience in the face of challenges is commendable.",
    "You're a fantastic listener and always offer support.",
    "The love you give is unconditional and boundless.",
    "You have an incredible sense of style.",
    "Your adventurous spirit makes life exciting.",
    "You bring out the best in those around you.",
    "Your warmth and kindness make the world a better place.",
    "You have a way of making even the simplest things magical.",
    "Your thoughtfulness and consideration make you stand out.",
    "You're a constant source of comfort and solace.",
    "The way you handle stress with calmness is admirable.",
    "Your authenticity is refreshing.",
    "You have a magnetic personality that draws people in.",
    "Your dedication to personal growth is inspiring.",
    "The way you make me feel loved and cherished is unparalleled.",
    "Your humility despite your accomplishments is humbling.",
    "You have a beautiful mind that constantly amazes me.",
    "Your dedication to your passions is contagious.",
    "You're my partner in crime, and I cherish every moment with you.",
    "Your ability to find joy in the little things is a gift.",
    "You have a gentle spirit that soothes the soul.",
    "Your ability to forgive and let go is a testament to your strength.",
    "You're a beacon of positivity in a sometimes challenging world.",
    "Your inner beauty shines brighter than any external beauty.",
    "You have a way of turning ordinary moments into extraordinary memories.",
    "Your resilience in the face of adversity is inspiring.",
    "You're a true friend and confidante.",
    "Your unwavering support is my anchor.",
    "You have a natural grace and elegance.",
    "Your wisdom surpasses your years.",
    "You're a constant source of encouragement.",
    "Your capacity for love knows no bounds.",
    "You have a charming and infectious laugh.",
    "Your curiosity about the world is contagious.",
    "You have a heart full of love and compassion.",
    "Your commitment to self-improvement is commendable.",
    "You make even the mundane tasks enjoyable.",
    "Your unwavering faith in the goodness of people is inspiring.",
    "You're a source of strength and comfort in difficult times.",
    "Your ability to find beauty in simplicity is admirable.",
    "You're my rock, always steady and supportive.",
    "Your integrity is unwavering.",
    "You have a captivating presence that lights up the room.",
    "Your ability to see the best in others is a rare and beautiful trait.",
    "You have a radiant spirit that brightens even the darkest days.",
    "You're a true treasure in my life.",
    "Your sense of adventure adds excitement to every day.",
    "You have a way of making challenges seem conquerable.",
    "Your commitment to your values is inspiring.",
    "You bring out the best in me.",
    "Your perseverance in the face of obstacles is commendable.",
    "You have a nurturing and caring nature.",
    "Your love is the most precious gift I've ever received.",
    "You have a contagious enthusiasm for life.",
    "You make me believe in the power of love.",
    "Your authenticity is a breath of fresh air.",
    "You have an incredible ability to make others feel seen and heard.",
    "Your humility makes you truly remarkable.",
    "You're the most beautiful person, inside and out.",
    "Your presence is a blessing in my life.",
    "You're my best friend and my greatest supporter.",
    "Your grace and poise are truly admirable.",
    "You have a heart that overflows with kindness and compassion.",
    "Your love is my greatest treasure.",
    "You have a way of making every day brighter.",
    "Your kindness towards others is a reflection of your beautiful soul.",
    "You're the epitome of beauty and grace.",
    "Your love has the power to heal and uplift.",
    "You have a unique and captivating charm.",
    "Your laughter is the sweetest melody.",
    "You make every moment special.",
    "Your love is the anchor that keeps me grounded.",
    "You're the most beautiful person I know, inside and out.",
    "Your love is a source of endless joy in my life."
];

function showRandomReason() {
    const randomIndex = Math.floor(Math.random() * reasons.length);
    const reasonDisplay = document.getElementById("reasonDisplay");
    reasonDisplay.textContent = reasons[randomIndex];
}
